In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("salaries_by_college_major.csv")

In [ ]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [ ]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [ ]:
clean_df = df.dropna()

In [ ]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
clean_df["Starting Median Salary"]

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [ ]:
clean_df["Starting Median Salary"].max()

74300.0

In [ ]:
clean_df["Starting Median Salary"].idxmax()

43

In [ ]:
clean_df["Undergraduate Major"].loc[43]

'Physician Assistant'

In [ ]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [ ]:
clean_df["Mid-Career Median Salary"].idxmax()

8

In [ ]:
clean_df["Undergraduate Major"].loc[8]

'Chemical Engineering'

In [ ]:
clean_df["Starting Median Salary"].loc[8]

63200.0

In [ ]:
clean_df["Starting Median Salary"].min()

34000.0

In [ ]:
clean_df["Starting Median Salary"].idxmin()

49

In [ ]:
clean_df["Undergraduate Major"].loc[49]

'Spanish'

In [ ]:
clean_df["Mid-Career Median Salary"].min()

52000.0

In [ ]:
clean_df["Mid-Career Median Salary"].idxmin()

18

In [ ]:
clean_df["Undergraduate Major"].loc[18]

'Education'

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df["Mid-Career 10th Percentile Salary"]

In [ ]:
clean_df.insert(1, "Spread", spread_col)

In [ ]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
low_risk = clean_df.sort_values("Spread")

In [ ]:
low_risk.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business

In [ ]:
low_risk[["Undergraduate Major", "Spread"]].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [ ]:
low_risk["Undergraduate Major", "Spread"].head()

KeyError: ignored

In [ ]:
low_risk[["Undergraduate Major", "Spread"]].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [ ]:
low_risk[["Undergraduate Major", "Spread"]].tail()

   Undergraduate Major    Spread
42          Philosophy  132500.0
36           Marketing  132900.0
37                Math  137800.0
22             Finance  147800.0
17           Economics  159400.0

In [ ]:
high_potential = clean_df.sort_values("Mid-Career 90th Percentile Salary")

In [ ]:
high_potential.tail()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business

In [ ]:
high_potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].tail()

     Undergraduate Major  Mid-Career 90th Percentile Salary
44               Physics                           178000.0
37                  Math                           183000.0
8   Chemical Engineering                           194000.0
22               Finance                           195000.0
17             Economics                           210000.0

In [ ]:
highest_spread = clean_df.sort_values("Mid-Career Median Salary", ascending=False)

In [ ]:
highest_spread[["Mid-Career Median Salary", "Undergraduate Major"]].head()

    Mid-Career Median Salary     Undergraduate Major
8                   107000.0    Chemical Engineering
12                  105000.0    Computer Engineering
19                  103000.0  Electrical Engineering
1                   101000.0   Aerospace Engineering
17                   98600.0               Economics

In [ ]:
clean_df.group_by("Group").count()

AttributeError: ignored

In [ ]:
clean_df.groupby("Group").count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [ ]:
clean_df.groupby("Group").mean()

<ipython-input-42-efdc932833d8>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby("Group").mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,103958.333333,44633.333333,75083.333333,43566.666667,147525.000000
HASS,95218.181818,37186.363636,62968.181818,34145.454545,129363.636364
STEM,101600.000000,53862.500000,90812.500000,56025.000000,157625.000000

In [ ]:
pd.options.display.float_format = "{:,.2f}".format

In [ ]:
clean_df.options.display.float_format = "{:,.2f}".format

AttributeError: ignored

In [ ]:
clean_df.groupby("Group").mean()

<ipython-input-45-efdc932833d8>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby("Group").mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"

In [ ]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [ ]:
df.findna()

AttributeError: ignored